backend:
  name: github
  repo: saintfish/cwts-www
  branch: cms-test
media_folder: "/public/uploads"
public_folder: "/uploads"
collections:
  - name: zh-about
    label: 基神介绍
    folder: src/content/pages/zh/about
    create: false
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
  - name: en-about
    label: About
    folder: src/content/pages/en/about
    create: false
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
  - name: en-academic
    label: Academic
    folder: src/content/pages/en/academic
    create: false
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
